### ISSUE TITLE
Columns too small to view

### ISSUE THREAD

**Issue by wldcordeiro** [benjaminRomano/linter-manager#4]
I'm not sure if this is an issue with linter-manager or bottom-dock, but when I use it my columns look like this and I can't resize them. 
![selection_006](https://cloud.githubusercontent.com/assets/580982/10204502/59a6531c-6779-11e5-9415-d90d54877c99.png)

**Comment by benjaminRomano** [comment]
if you click and drag one of the columns slighty, it should resize them to fit. After that they can be resized.

I'll try and see if I can fix this to work on startup

**Comment by wldcordeiro** [comment]
Ah yeah, that did the trick. The odd thing is that if you hover over where the column end is, your cursor changes but trying to click and drag there doesn't work.
