### ISSUE TITLE
Not working consistently

### ISSUE THREAD

**Issue by jerone** [benjaminRomano/linter-manager#9]
I'm having problem getting this package to work consistency. 

When I start Atom I can only open the docking panel by using the <kbd>Package</kbd> > <kbd>bottom-dock</kbd> menu item. When using the keybinding <kbd>ctrl-k ctrl-t</kbd> it does nothing (no console errors). I verified through Key Binding Resolver that the keybinding is linked to the bottom-dock package.

Then when the panel is open it shows the table columns very small. Previously closed issue https://github.com/benjaminRomano/linter-manager/issues/4 proposed solution of dragging the columns handles does nothing. The only solution is to let the table view repaint (e.g. by resizing window).
![linter manager](https://cloud.githubusercontent.com/assets/55841/13033478/022bf794-d318-11e5-909f-df5546e76b9e.png)

After closing the panel, I can't open it again. Not with keybinding or <kbd>Package</kbd> menu item.

I understand that some issues mentioned here should probably opened on the [bottom-dock](https://github.com/benjaminRomano/bottom-dock) repo, but I wanted to make sure I'm not missing anything.

Awesome packages btw!

---

_Atom 1.6.0-beta3
Linter Manager 0.2.8
bottom-dock 0.3.7
Linter 1.11.3
And a few linter plugins, like linter-markdown 1.4.2
Windows 7_

**Comment by benjaminRomano** [comment]
It looks like you are running atom 1.6.0 that might be a potential problem. Did this previously work for you in atom 1.5?

Also, I'd recommend maybe reinstalling both the linter-manager and bottom-dock. 

As for the small tabs, I unfortunately haven't been able to find a simple way to resolve that. The simplest fix as you said is just to resize the window.

**Comment by jerone** [comment]
I can actually reproduce the same issues on another setup with Atom 1.5.3

**Comment by benjaminRomano** [comment]
Are there any errors in the console? If there are could you take a screenshot of them. You can open up the console with <kbd>ctrl+alt+i</kbd>

**Comment by jerone** [comment]
As mentioned in the first post, no console errors.

**Comment by benjaminRomano** [comment]
Oh my bad, I missed that.

So when you say closing the panel, do you mean pressing the red X button?

If so, that actually removes the linter-manager panel, and if there are no other panels, bottom-dock is hidden (until another panel is opened and bottom-dock is toggled to be shown).

**Comment by jerone** [comment]
> So when you say closing the panel, do you mean pressing the red X button?

Yes

**Comment by benjaminRomano** [comment]
You mentioned, you go to <kbd>Package</kbd> > <kbd>bottom-dock</kbd>. When you access that menu which option are you clicking? 

After you press the red X, you have to either use <kbd>Package</kbd> > <kbd>bottom-dock</kbd> > <kbd>Add Linter Pane</kbd> or <kbd>ctrl+k ctrl+i</kbd>, and then toggle bottom-dock to reshow.

Does this solve your problem?

**Comment by jerone** [comment]
Oke, I get it now. The X doesn't hide the bottom-dock, but it actually closes the linter pane. To me this is a bit counter intuitive as the linter-manager just uses the bottom-dock. 

I don't have more bottom-dock plugins installed, but how does that work? Does it open multiple docks or shows it all plugins as tabs within the dock?

**Comment by benjaminRomano** [comment]
Yep, the X just closes the current pane. I'll add a tooltip to make that more clear.

If you have multiple panes open it adds tabs to the bottom for switching between them. You can test this by adding a 2nd linter-manager pane. This works since you can have multiple panes of the same type in bottom-dock.

**Comment by jerone** [comment]
Is it an idea to give the dock tabs a close button (just like regular tabs) and use the top right close button as a close (read toggle) button for the dock (similar to the statusbar tile)?

**Comment by benjaminRomano** [comment]
I've decided to remove the close button. It has caused more confusion than it's worth.

Also as for adding a close button to the tabs, I implemented it at the beginning but didn't like how it felt. It was too easy to click the close button accidentally since my tabs are smaller than the ones up at the top.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
